development:
  dialect: postgres
  database: brokestest_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/brokestest_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://zoddzknziofhjj:61f672b8c41a7c1839cbbd0bce0f6a40aadfa8f423852015a50aac86220e0587@ec2-54-225-103-255.compute-1.amazonaws.com:5432/df9ggjhidrm7bu?sslmode=disable"}}