package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/markbates/pop"
	"github.com/pavanas/brokestest/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Meeting)
// DB Table: Plural (meetings)
// Resource: Plural (Meetings)
// Path: Plural (/meetings)
// View Template Folder: Plural (/templates/meetings/)

// MeetingsResource is the resource for the Meeting model
type MeetingsResource struct {
	buffalo.Resource
}

// List gets all Meetings. This function is mapped to the path
// GET /meetings
func (v MeetingsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	meetings := &models.Meetings{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Meetings from the DB
	if err := q.All(meetings); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the headers so clients know how to paginate.
	c.Response().Header().Set("X-Pagination", q.Paginator.String())

	return c.Render(200, r.JSON(meetings))
}

// Show gets the data for one Meeting. This function is mapped to
// the path GET /meetings/{meeting_id}
func (v MeetingsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Meeting
	meeting := &models.Meeting{}

	// To find the Meeting the parameter meeting_id is used.
	if err := tx.Find(meeting, c.Param("meeting_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.JSON(meeting))
}

// New default implementation. Returns a 404
func (v MeetingsResource) New(c buffalo.Context) error {
	return c.Error(404, errors.New("not available"))
}

// Create adds a Meeting to the DB. This function is mapped to the
// path POST /meetings
func (v MeetingsResource) Create(c buffalo.Context) error {
	// Allocate an empty Meeting
	meeting := &models.Meeting{}

	// Bind meeting to the html form elements
	if err := c.Bind(meeting); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(meeting)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Render errors as JSON
		return c.Render(400, r.JSON(verrs))
	}

	return c.Render(201, r.JSON(meeting))
}

// Edit default implementation. Returns a 404
func (v MeetingsResource) Edit(c buffalo.Context) error {
	return c.Error(404, errors.New("not available"))
}

// Update changes a Meeting in the DB. This function is mapped to
// the path PUT /meetings/{meeting_id}
func (v MeetingsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Meeting
	meeting := &models.Meeting{}

	if err := tx.Find(meeting, c.Param("meeting_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Meeting to the html form elements
	if err := c.Bind(meeting); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(meeting)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Render errors as JSON
		return c.Render(400, r.JSON(verrs))
	}

	return c.Render(200, r.JSON(meeting))
}

// Destroy deletes a Meeting from the DB. This function is mapped
// to the path DELETE /meetings/{meeting_id}
func (v MeetingsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Meeting
	meeting := &models.Meeting{}

	// To find the Meeting the parameter meeting_id is used.
	if err := tx.Find(meeting, c.Param("meeting_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(meeting); err != nil {
		return errors.WithStack(err)
	}

	return c.Render(200, r.JSON(meeting))
}
